version: '3'
services: 
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    command: ['npm', 'run', 'test']
    environment: 
      CI: 'true'
